/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simpleapp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void appHasAnotherGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getAnotherGreeting(), "app should have a second greeting");
    }

    @Test
    void appHasHi() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.sayHi(), "hi");
    }
}
