/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simpleapp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    App classUnderTest = new App();

    @Test
    void appHasAGreeting() {
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void appHasAnotherGreeting() {
        assertNotNull(classUnderTest.getAnotherGreeting(), "app should have a second greeting");
    }

    @Test
    void test1() {
        assertEquals(classUnderTest.getAnotherGreeting(), "Greetings!");
    }
}
